/**
 * promptCompiler.js
 * 
 * Simplified compiler for Veo 3.1.
 * Since Stage 2 (Gemini) already generates high-fidelity, policy-compliant prompts,
 * this function functions as a pass-through to avoid confusing the Veo video model
 * with meta-instructions.
 */

export const compileVeoPrompt = ({ narrativeBeat, project = {}, options = {} }) => {
    // Veo 3.1 expects a direct visual description.
    // Meta-instructions (like "You are generating...") trigger RAI filters 
    // because they contain blocked keywords (even in negative contexts) 
    // and confuse the visual encoder.

    // We strictly return the narrative beat generated by Gemini.
    return narrativeBeat.trim();
};
