import { Storage } from '@google-cloud/storage';
import fs from 'fs/promises';
import path from 'path';
import crypto from 'crypto';

const getEnvValue = (keys) => {
    for (const key of keys) {
        const value = process.env[key];
        if (value) return value;
    }
    return undefined;
};

export const getStorageConfig = () => {
    const bucket = getEnvValue(['GCP_BUCKET_NAME', 'GOOGLE_CLOUD_BUCKET']);
    const objectPrefix = (getEnvValue(['GCP_BUCKET_PREFIX', 'STORAGE_OBJECT_PREFIX']) || 'generated').replace(/\/+$/g, '');
    let projectId = getEnvValue(['GCP_PROJECT_ID', 'GOOGLE_CLOUD_PROJECT']);
    let gcpSaKeyRaw = process.env.GCP_SA_KEY;

    // Auto-parse Project ID from the Service Account JSON if it is missing
    if (!projectId && gcpSaKeyRaw) {
        try {
            const parsedKey = JSON.parse(gcpSaKeyRaw);
            projectId = parsedKey.project_id;
        } catch (e) {
            // Ignore parse errors
        }
    }

    if (projectId) projectId = projectId.trim();

    return { bucket, projectId, objectPrefix, gcpSaKeyRaw };
};

export const getGcsClient = () => {
    const config = getStorageConfig();

    const clientConfig = {};
    if (config.projectId) {
        clientConfig.projectId = config.projectId;
    }

    let parsedSuccessfully = false;
    if (config.gcpSaKeyRaw) {
        try {
            let cleanedKey = config.gcpSaKeyRaw;
            if (cleanedKey.includes('\\"')) cleanedKey = cleanedKey.replace(/\\"/g, '"');

            const parsed = JSON.parse(cleanedKey);
            if (parsed.private_key && parsed.private_key.includes('\\n')) {
                parsed.private_key = parsed.private_key.replace(/\\n/g, '\n');
            }
            clientConfig.credentials = parsed;
            parsedSuccessfully = true;
        } catch (e) {
            console.error('[Storage] Failed to parse GCP_SA_KEY JSON. Falling back to local keyfile.');
        }
    }

    if (!parsedSuccessfully) {
        // Fallback to local key file generated by start.sh or local dev
        const keyPath = path.resolve(process.cwd(), 'vertex-key.json');
        clientConfig.keyFilename = keyPath;
    }

    return new Storage(clientConfig);
};

export const isStorageConfigured = () => {
    const { bucket } = getStorageConfig();
    const configured = Boolean(bucket);

    if (!isStorageConfigured._logged) {
        console.log('[StorageConfig] Using Google Cloud Storage');
        console.log('[StorageConfig] bucket:', bucket ? 'SET' : 'MISSING');
        console.log('[StorageConfig] configured:', configured);
        isStorageConfigured._logged = true;
    }
    return configured;
};

export const buildObjectKey = ({ userId, prefix = 'generated', extension = '' }) => {
    const safePrefix = prefix.replace(/\/+$/g, '');
    const ext = extension.startsWith('.') ? extension : extension ? `.${extension}` : '';
    return `${safePrefix}/${userId}/${crypto.randomUUID()}${ext}`;
};

export const getObjectPrefix = () => {
    return getStorageConfig().objectPrefix;
};

export const getPublicUrl = (key) => {
    const { bucket } = getStorageConfig();
    return `https://storage.googleapis.com/${bucket}/${key}`;
};

export const uploadFileToStorage = async ({ filePath, key, contentType }) => {
    const { bucket } = getStorageConfig();
    if (!bucket) throw new Error('Storage bucket is not configured');

    const storage = getGcsClient();
    const bucketObj = storage.bucket(bucket);
    const file = bucketObj.file(key);

    await file.save(await fs.readFile(filePath), {
        metadata: {
            contentType: contentType || getContentTypeForPath(filePath),
            contentDisposition: 'inline',
        },
        public: true, // Make the file publicly readable for EvoLink/Backend services
        resumable: false
    });

    return getPublicUrl(key);
};

export const uploadDirectoryToStorage = async ({ dirPath, prefix }) => {
    const { bucket } = getStorageConfig();
    if (!bucket) throw new Error('Storage bucket is not configured');

    const storage = getGcsClient();
    const bucketObj = storage.bucket(bucket);
    const dirFiles = await fs.readdir(dirPath);
    let masterUrl = '';

    for (const fileName of dirFiles) {
        const filePath = path.join(dirPath, fileName);
        const fileContent = await fs.readFile(filePath);
        const key = `${prefix}/${fileName}`;

        let contentType = 'application/octet-stream';
        if (fileName.endsWith('.m3u8')) contentType = 'application/vnd.apple.mpegurl';
        else if (fileName.endsWith('.ts')) contentType = 'video/mp2t';

        const file = bucketObj.file(key);
        await file.save(fileContent, {
            metadata: { contentType },
            resumable: false
        });

        if (fileName.endsWith('.m3u8')) {
            masterUrl = getPublicUrl(key);
        }
    }

    return masterUrl;
};

export const uploadBufferToStorage = async ({ buffer, key, contentType }) => {
    const { bucket } = getStorageConfig();
    if (!bucket) throw new Error('Storage bucket is not configured');

    const storage = getGcsClient();
    const bucketObj = storage.bucket(bucket);
    const file = bucketObj.file(key);

    await file.save(buffer, {
        metadata: {
            contentType: contentType || 'application/octet-stream',
            contentDisposition: 'inline',
        },
        public: true, // Make the file publicly readable for EvoLink/Backend services
        resumable: false
    });

    return getPublicUrl(key);
};

export const getContentTypeForPath = (filePath) => {
    const ext = path.extname(filePath).toLowerCase();
    switch (ext) {
        case '.mp4': return 'video/mp4';
        case '.mov': return 'video/quicktime';
        case '.png': return 'image/png';
        case '.jpg':
        case '.jpeg': return 'image/jpeg';
        case '.webp': return 'image/webp';
        default: return 'application/octet-stream';
    }
};

// Polvfill AWS SDK presigned functions by converting them to Google Signed URLs
export const getPresignedUploadUrl = async ({ key, contentType, expiresIn = 900 }) => {
    const { bucket } = getStorageConfig();
    if (!bucket) throw new Error('Storage bucket is not configured');

    const storage = getGcsClient();
    const [url] = await storage.bucket(bucket).file(key).getSignedUrl({
        version: 'v4',
        action: 'write',
        expires: Date.now() + (expiresIn * 1000),
        contentType: contentType || 'application/octet-stream'
    });
    return url;
};

export const extractKeyFromUrl = (url) => {
    if (!url) return null;
    try {
        const urlObj = new URL(url);
        let p = urlObj.pathname;
        if (p.startsWith('/')) p = p.substring(1);

        // Strip bucket name from path if using `storage.googleapis.com`/bucket/key format
        const { bucket } = getStorageConfig();
        if (bucket && p.startsWith(`${bucket}/`)) {
            return p.substring(bucket.length + 1);
        }
        return p;
    } catch (e) {
        return url;
    }
};

export const getPresignedDownloadUrl = async ({ key, expiresIn = 3600, download = false, contentType = null }) => {
    const { bucket } = getStorageConfig();
    if (!bucket) throw new Error('Storage bucket is not configured');

    const storage = getGcsClient();
    const options = {
        version: 'v4',
        action: 'read',
        expires: Date.now() + (expiresIn * 1000)
    };

    if (download) {
        const ext = path.extname(key) || '.mp4';
        options.responseDisposition = `attachment; filename="technov-asset-${Date.now()}${ext}"`;
    }

    const [url] = await storage.bucket(bucket).file(key).getSignedUrl(options);
    return url;
};
